package org.lc.video.model;

import java.util.Date;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.admin_id
     *
     * @mbg.generated Thu May 10 19:03:35 CST 2018
     */
    private Long adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.name
     *
     * @mbg.generated Thu May 10 19:03:35 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.password
     *
     * @mbg.generated Thu May 10 19:03:35 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.is_delete
     *
     * @mbg.generated Thu May 10 19:03:35 CST 2018
     */
    private Boolean delete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.gmt_create
     *
     * @mbg.generated Thu May 10 19:03:35 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.gmt_modified
     *
     * @mbg.generated Thu May 10 19:03:35 CST 2018
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.admin_id
     *
     * @return the value of admin_user.admin_id
     *
     * @mbg.generated Thu May 10 19:03:35 CST 2018
     */
    public Long getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.admin_id
     *
     * @param adminId the value for admin_user.admin_id
     *
     * @mbg.generated Thu May 10 19:03:35 CST 2018
     */
    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.name
     *
     * @return the value of admin_user.name
     *
     * @mbg.generated Thu May 10 19:03:35 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.name
     *
     * @param name the value for admin_user.name
     *
     * @mbg.generated Thu May 10 19:03:35 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.password
     *
     * @return the value of admin_user.password
     *
     * @mbg.generated Thu May 10 19:03:35 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.password
     *
     * @param password the value for admin_user.password
     *
     * @mbg.generated Thu May 10 19:03:35 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.is_delete
     *
     * @return the value of admin_user.is_delete
     *
     * @mbg.generated Thu May 10 19:03:35 CST 2018
     */
    public Boolean getDelete() {
        return delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.is_delete
     *
     * @param delete the value for admin_user.is_delete
     *
     * @mbg.generated Thu May 10 19:03:35 CST 2018
     */
    public void setDelete(Boolean delete) {
        this.delete = delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.gmt_create
     *
     * @return the value of admin_user.gmt_create
     *
     * @mbg.generated Thu May 10 19:03:35 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.gmt_create
     *
     * @param gmtCreate the value for admin_user.gmt_create
     *
     * @mbg.generated Thu May 10 19:03:35 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.gmt_modified
     *
     * @return the value of admin_user.gmt_modified
     *
     * @mbg.generated Thu May 10 19:03:35 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.gmt_modified
     *
     * @param gmtModified the value for admin_user.gmt_modified
     *
     * @mbg.generated Thu May 10 19:03:35 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}