package org.lc.video.model;

import java.util.Date;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_id
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    private Long courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.gmt_create
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.gmt_modified
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.create_admin
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    private Long createAdmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.modified_admin
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    private Long modifiedAdmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.title
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.description
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.subject_id
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    private Long subjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.is_delete
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    private Boolean delete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_id
     *
     * @return the value of course.course_id
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    public Long getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_id
     *
     * @param courseId the value for course.course_id
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.gmt_create
     *
     * @return the value of course.gmt_create
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.gmt_create
     *
     * @param gmtCreate the value for course.gmt_create
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.gmt_modified
     *
     * @return the value of course.gmt_modified
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.gmt_modified
     *
     * @param gmtModified the value for course.gmt_modified
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.create_admin
     *
     * @return the value of course.create_admin
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    public Long getCreateAdmin() {
        return createAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.create_admin
     *
     * @param createAdmin the value for course.create_admin
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    public void setCreateAdmin(Long createAdmin) {
        this.createAdmin = createAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.modified_admin
     *
     * @return the value of course.modified_admin
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    public Long getModifiedAdmin() {
        return modifiedAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.modified_admin
     *
     * @param modifiedAdmin the value for course.modified_admin
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    public void setModifiedAdmin(Long modifiedAdmin) {
        this.modifiedAdmin = modifiedAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.title
     *
     * @return the value of course.title
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.title
     *
     * @param title the value for course.title
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.description
     *
     * @return the value of course.description
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.description
     *
     * @param description the value for course.description
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.subject_id
     *
     * @return the value of course.subject_id
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    public Long getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.subject_id
     *
     * @param subjectId the value for course.subject_id
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    public void setSubjectId(Long subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.is_delete
     *
     * @return the value of course.is_delete
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    public Boolean getDelete() {
        return delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.is_delete
     *
     * @param delete the value for course.is_delete
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    public void setDelete(Boolean delete) {
        this.delete = delete;
    }


    @Override
    public String toString() {
        return "Course{" +
                "courseId=" + courseId +
                ", gmtCreate=" + gmtCreate +
                ", gmtModified=" + gmtModified +
                ", createAdmin=" + createAdmin +
                ", modifiedAdmin=" + modifiedAdmin +
                ", title='" + title + '\'' +
                ", description='" + description + '\'' +
                ", subjectId=" + subjectId +
                ", delete=" + delete +
                '}';
    }
}