package org.lc.video.model;

import java.util.Date;

public class Subject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject.subject_id
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    private Long subjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject.gmt_create
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject.gmt_modified
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject.create_admin
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    private Long createAdmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject.modified_admin
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    private Long modifiedAdmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject.title
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject.is_delete
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    private Boolean delete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject.subject_id
     *
     * @return the value of subject.subject_id
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    public Long getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject.subject_id
     *
     * @param subjectId the value for subject.subject_id
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    public void setSubjectId(Long subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject.gmt_create
     *
     * @return the value of subject.gmt_create
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject.gmt_create
     *
     * @param gmtCreate the value for subject.gmt_create
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject.gmt_modified
     *
     * @return the value of subject.gmt_modified
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject.gmt_modified
     *
     * @param gmtModified the value for subject.gmt_modified
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject.create_admin
     *
     * @return the value of subject.create_admin
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    public Long getCreateAdmin() {
        return createAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject.create_admin
     *
     * @param createAdmin the value for subject.create_admin
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    public void setCreateAdmin(Long createAdmin) {
        this.createAdmin = createAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject.modified_admin
     *
     * @return the value of subject.modified_admin
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    public Long getModifiedAdmin() {
        return modifiedAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject.modified_admin
     *
     * @param modifiedAdmin the value for subject.modified_admin
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    public void setModifiedAdmin(Long modifiedAdmin) {
        this.modifiedAdmin = modifiedAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject.title
     *
     * @return the value of subject.title
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject.title
     *
     * @param title the value for subject.title
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject.is_delete
     *
     * @return the value of subject.is_delete
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    public Boolean getDelete() {
        return delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject.is_delete
     *
     * @param delete the value for subject.is_delete
     *
     * @mbg.generated Thu May 10 19:32:54 CST 2018
     */
    public void setDelete(Boolean delete) {
        this.delete = delete;
    }
}